language: ruby

rvm:
  - 2.3.3

cache:
  bundler: true

services:
  - docker

before_script:
  - docker-compose --version

script:
  - time make .env rspec

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - commit=$(git rev-parse HEAD)
  - docker build -t gojekfarm/kingsly:$commit -t gojekfarm/kingsly:latest .
  - docker push gojekfarm/kingsly:$commit
  - docker push gojekfarm/kingsly:latest
