version: '3'
services:
  kingsly-server:
    build:
      context: .
    ports:
     - "8080:8080"
    depends_on:
     - sqlite
    volumes:
     - ./:/usr/src/app
     - 'bundle_cache:/bundle'
    environment:
    - RAILS_ENV=development
    env_file:
      - config/application.yml
    working_dir: /usr/src/app
    entrypoint: [/docker-entrypoint.sh]
    command: ["bundle", "exec", "rails", "s", "-p", "8080", "-b", "0.0.0.0"]
    tty: true
    stdin_open: true

  sqlite:
      image: nouchka/sqlite3
      ports:
        - "5432:5432"
      stdin_open: true
      tty: true
      volumes:
         - ./db/:/root/db/
volumes:
  sqlite:
  bundle_cache:

