version: '3'

services:
  kingsly-server:
    build:
      context: .
    ports:
     - "8080:8080"
    depends_on:
     - postgres
    env_file:
      - .env
    volumes:
     - ./:/usr/src/app
     - 'bundle_cache:/bundle'
    environment:
    - RAILS_ENV=development
    working_dir: /usr/src/app
    entrypoint: [/docker-entrypoint.sh]
    command: >
      bash -c "rails db:create db:migrate
      && bundle exec rails s -p 8080 -b 0.0.0.0"
    tty: true
    stdin_open: true

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/root/db/

volumes:
  postgres:
  bundle_cache:
