default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= Figaro.env.DB_HOST%>
  database: <%= Figaro.env.DB_NAME%>
  username: <%= Figaro.env.DB_USERNAME%>
  password: <%= Figaro.env.DB_PASSWORD%>
  pool:     <%= Figaro.env.DB_CONN_POOL%>
  timeout:  <%= Figaro.env.DB_TIMEOUT%>

development:
  <<: *default

test:
  <<: *default
  database: kingsly_test

production:
  <<: *default
