default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  database: <%= ENV.fetch("DB_NAME") { "kingsly" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASWORD") { "" } %>
  pool: <%= ENV.fetch("DB_CONN_POOL") { 5 } %>
  timeout: <%= ENV.fetch("DB_TIMEOUT") { 5000 } %>

development:
  <<: *default

test:
  <<: *default
  database: kingsly_test

production:
  <<: *default
